version: '3.8'

volumes:

  staticfiles:


services:

  web:

    build: .
    volumes:
      - staticfiles:/app/static/

    restart: always
    ports:
      - '8000:8000'
    env_file:
      - ./.env 

  
  
  web1:
    image: nginx:1.19.6
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - staticfiles:/app/static/

    restart: always
    ports:
      - '80:80'
    depends_on:
      - web
